### ISSUE TITLE
Errors when training FlatNet-gen

### ISSUE THREAD

**Issue by JW-bnc** [siddiquesalman/flatnet-separable#1]
I was trying to train the non-separable model of FlatNet from scratch by running 'python train.py with ours_meas_1280_1408 -p', but I ran into some problems. I can successfully train FlatNet-sep and use the trained model for reconstruction using explore_flatnet_gen.ipynb. I have Python 3.8.12 and Pytorch 1.7.1. Thank you for your help!

When set resume = True, I got the following error:
ERROR - Train - Failed after 0:00:02!
Traceback (most recent call last):
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\experiment.py", line 312, in run_commandline
    return self.run(
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\experiment.py", line 276, in run
    run()
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\config\captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "train.py", line 109, in main
    ), global_step, start_epoch, loss = load_models(
  File "E:\FlatNet-code\flatnet-flatnet-gen\utils\train_helper.py", line 185, in load_models
    optimizer.load_state_dict(checkpoint["optimizer"])
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\torch\optim\optimizer.py", line 124, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 63, in <module>
    def main(_run):
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\experiment.py", line 190, in automain
    self.run_commandline()
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\experiment.py", line 347, in run_commandline
    print_filtered_stacktrace()
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\utils.py", line 493, in print_filtered_stacktrace
    print(format_filtered_stacktrace(filter_traceback), file=sys.stderr)
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\utils.py", line 528, in format_filtered_stacktrace
    return "".join(filtered_traceback_format(tb_exception))
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\utils.py", line 568, in filtered_traceback_format
    current_tb = tb_exception.exc_traceback
AttributeError: 'TracebackException' object has no attribute 'exc_traceback'

When set resume = False, I got the following error:
RROR - Train - Failed after 0:00:03!                                                                                      | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\experiment.py", line 312, in run_commandline
    return self.run(
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\experiment.py", line 276, in run
    run()
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\config\captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "train.py", line 200, in main
    for i, batch in enumerate(data.train_loader):
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'utils.tupperware.Tupperware'>: attribute lookup Tupperware on utils.tupperware failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 63, in <module>
    def main(_run):
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\experiment.py", line 190, in automain
    self.run_commandline()
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\experiment.py", line 347, in run_commandline
    print_filtered_stacktrace()
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\utils.py", line 493, in print_filtered_stacktrace
    print(format_filtered_stacktrace(filter_traceback), file=sys.stderr)
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\utils.py", line 528, in format_filtered_stacktrace
    return "".join(filtered_traceback_format(tb_exception))
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\site-packages\sacred\utils.py", line 568, in filtered_traceback_format
    current_tb = tb_exception.exc_traceback
AttributeError: 'TracebackException' object has no attribute 'exc_traceback'
  0%|          | 0/9895 [00:00<?, ?it/s]
  0%|          | 0/100 [00:00<?, ?it/s]

(FlatNet) E:\FlatNet-code\flatnet-flatnet-gen>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Jimin\anaconda3\envs\FlatNet\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by varun19299** [comment]
If you wish to train from scratch, please do not use the `resume` flag. If you would like to fine-tune instead set `finetune=True`.
